[build]
  publish = "publish"
  command = """
    pip install -r requirements.txt && \
    jupyter book build --html && \
    mkdir -p publish$BASE_URL && \
    mv _build/html/* publish$BASE_URL/
  """

[build.environment]
  BASE_URL = "/geolab"
  PYTHON_VERSION = "3.12"
