# Building this repo with Python requirements.txt and Jupyter Book
# (as opposed to using Node.js and mystmd) in case we want to use some
# other Python packages such as notebooks in the future.
[build]
  publish = "publish"
  command = """
    set -e

    curl -fsSL https://bun.sh/install | bash
    export PATH="$HOME/.bun/bin:$PATH"
    bun --version

    git clone --depth 1 --branch index-redirect-hydration \
      https://github.com/chad-earthscope/mystmd.git ../mystmd-fork
    (cd ../mystmd-fork && bun install && bun run build && bun run link)

    git clone --depth 1 --branch toc-baseurl-hydration \
      https://github.com/chad-earthscope/myst-theme.git ../myst-theme-fork
    (cd ../myst-theme-fork && bun install && make build-book)

    myst --version
    myst build --html

    mkdir -p "publish$BASE_URL" && \
    mv _build/html/* "publish$BASE_URL/" && \
    printf '/  %s/  301\n' "$BASE_URL" > publish/_redirects
  """

[build.environment]
  BASE_URL = "/geolab"
  PYTHON_VERSION = "3.12"
